Repository Samourai-Wallet/samourai-dojo, pull requests merged in 2019-07, with the labels that each got.

#27 rework external loop of Orchestrator
  pushtx/orchestrator.js
Labels: bug

#25 force the tracker to derive next indices if a hole is detected
  lib/db/mysql-db-wrapper.js
  tracker/transaction.js
Labels: bug

#28 rework RemoteImporter
  lib/remote-importer/btccom-wrapper.js
  lib/remote-importer/sources-mainnet.js
  lib/remote-importer/sources-testnet.js
  lib/remote-importer/sources.js
Labels: enhancement

#32 change the conditions switching the startup mode of the tracker
  tracker/blockchain-processor.js
Labels: enhancement, my-dojo

#33 Check authentication with admin key
  static/admin/index.js
  static/admin/lib/auth-utils.js
Labels: enhancement, maintenance tool, ux

#37 automatic redirect of onion address to maintenance tool
  docker/my-dojo/nginx/dojo.conf
Labels: enhancement, maintenance tool, ux

#38 dojo shutdown - replace sleep with static delay by docker wait
  docker/my-dojo/dojo.sh
Labels: enhancement, my-dojo

#41 update nodejs packages
  package-lock.json
  package.json
Labels: security

#42 Fix few typos, add backticks for config values
  doc/DOCKER_setup.md
Labels: documentation
